### ISSUE TITLE
Enhancement Request: Allow for inline checkbox form controls

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/gd-bs#12]
Bootstrap allows for checkbox form controls to appear "inline." It would be great if this could be added as an option when creating a checkbox control. Maybe an optional boolean parameter called "inline" could be used. 

The html would appear as follows:

```javascript
<div class="form-group form-check form-check-inline col">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
</div>
```

**Comment by gunjandatta** [comment]
I added this property to both the form control checkbox property and checkbox group. Let me know if you have any issues w/ it.
