### ISSUE TITLE
IDropdownItem Divider Functionality

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/gd-bs#2]
Adding the isDivider flag to an IDropdownItem does not render it as a divider element, or make it unselectable. It appears as a blank line, if text is not provided.

Example Code:

```javascript
options.push({
    isDivider:true
} as IDropdownItem);
```
vs
```javascript
options.push({
    text:"Regular Item",
    value: "Stuff"
} as IDropdownItem)
```

**Comment by gunjandatta** [comment]
Fixed in v1.2.0 gd-bs
Fixed in v1.5.7 gd-sprest-bs
