### ISSUE TITLE
Creating Form Column w Mult Classes Fails

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/gd-bs#20]
Using the following code to create a column (IFormColumn) in a row (IFormRow) results in the following error:

DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('text-right mr-1') contains HTML space characters, which are not valid in tokens.

```javascript
{
    control: {
        className: "text-right mr-1",
        onControlRendered: control => {
            control.el.innerHTML = `some content`;
        }
    }
} as Components.IFormColumn
```

**Comment by gunjandatta** [comment]
This was an old bug that wasn't applied to the form control. Fixed in v1.6.2.
