### ISSUE TITLE
Text field blank when value set to zero

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/gd-bs#22]
When setting the value property on an IFormControlPropsTextField to the number 0, the text field is blank.

```javascript
{
    control: {
        name: "example",        
        type: Components.FormControlTypes.TextField,
        value: 0,
    } as Components.IFormControlPropsTextField
}
```

**Comment by gunjandatta** [comment]
I updated the inputgroup component. This was a bug, but on further investigation, when you use a form it's best to use the "value" component to define the values for the form object. When passing in the number 0 as the value for the control, the properties has it defined as null for some reason. This was repeated in Edge and Chrome. If you use "0" instead, it will pass the value in and work.
