### ISSUE TITLE
No value of Dropdown after setItems

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/gd-bs#37]
Creating a Components.IFormControlPropsDropdown with an empty array of items, setting the items later with dropdown's function setItems, and then trying to get the value of the dropdown using the Components.IForm results in the value of the dropdown being undefined. Some example code below: 

Create the ddl control
```javascript
control: {
    label: "Change Requested Field:",
    name: "ChangeRequestedField",
    type: Components.FormControlTypes.Dropdown,
    items: [],
} as Components.IFormControlPropsDropdown
```

Based on some event, add the items to the ddl
```javascript
let changeRequestedField;

let ddlItems: Array<Components.IDropdownItem> = _form
    .controls
    .filter(c => c.props["canRequestChange"] === true)
    .map((control) => {
        return { text: control.props.label, value: control.props.name, data: control.props }
    });

changeRequestedField = _form.getControl("ChangeRequestedField");

if (changeRequestedField) 
    changeRequestedField.dropdown.setItems(ddlItems);   
```

Then try to get the value of the ddl when a button is clicked

```javascript
let values = _form.getValues();

let selectedFieldProps = values["ChangeRequestedField"]; //Results in undefined
```

**Comment by gunjandatta** [comment]
The comparison operator for determining the selected item for forms was failing due to leading/trailing spaces. This has been fixed in the latest version of the library.
