### ISSUE TITLE
Components.Dropdown improperly adding target attribute

### ISSUE THREAD

**Issue by Dade-R** [gunjandatta/gd-bs#38]
When rendering a new dropdown component, each item has a target attribute being improperly added.
```
let ddl = Components.Dropdown({
  el: el,
  label: "Click Here",
  type: Components.DropdownTypes.Secondary,
  items: [
    { text: "Select an item", value: "0", isHeader: true },
    { text: "Item1", value: "1" },
    { text: "Item2", value: "2" }
  ],
  onChange: (item: any, ev) => {
    console.log("You selected: " + item?.text + " with value: " + item?.value);
  }
});
```
Each <a> element has a target defined (and shouldn't), opening a new tab on each click. A target is not being defined in the code above, so this shouldn't be rendered in the markup. Markup result: `<a class="dropdown-item" href="#" target="_blank">Item1</a>`

I can add more code to remove the improper target attributes, like:
```
ddl.el.querySelectorAll(".dropdown-item").forEach((el: HTMLElement) => {
  el.removeAttribute("target");
});
```
But this should not be needed. The markup should be: `<a class="dropdown-item" href="#">Item1</a>` unless you are defining a target for the item.

**Comment by gunjandatta** [comment]
From further investigation of the code example provided, this was done via the SP.UI.ModalDialog. Setting the html element option changed the anchors to include this attribute. The core lib wasn't causing this issue.
