### ISSUE TITLE
Range isReadOnly Property Not Disabling Control

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/gd-bs#41]
When using the isReadonly property to create a Components.IFormControlPropsRange control on the Components.Form, the generated HTML uses the readonly tag, but should use disabled.

Current HTML output:

```html
<input type="range" class="form-control form-range" readonly>
```

Desired HTML output: 

```html
<input type="range" class="form-control form-range" id="disabledRange" disabled>
```

Reference: https://getbootstrap.com/docs/5.0/forms/range/

Example code: 

```javascript
{
    control: {
        label: "Test:",
        name: "TestRange",
        type: Components.FormControlTypes.Range,
        isReadonly: true,
    } as Components.IFormControlPropsRange
},
```

**Comment by gunjandatta** [comment]
Per the docs, I'll update both the readonly and disabled properties.
