### ISSUE TITLE
Suggestion - Allow Classes on Form Component Rows with Columns

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/gd-bs#5]
When adding a row to a Form component, the className and controlClassName properties are ignored if columns exist. 

```javascript
{
   className: "Example",
   controlClassName: "Example",
   columns: [
      { ... } 
   ]
}
```

**Comment by gunjandatta** [comment]
Fixed in v1.2.9. I also added a rowClassName to the form component. This will set the class name on the row element.
