### ISSUE TITLE
Give option to set colors for tooltip in DattaTables

### ISSUE THREAD

**Issue by zeroClassSOLDIER** [gunjandatta/gd-bs#50]
Current tool-tip accepts option to change the color of the word balloon to bootstrap primary and secondary, however does not accept other colors such as danger. Can a the DattaTable framework be adjusted so that if another option passed to "theme" it will cause the tool-tip to appear with that color?

![image](https://user-images.githubusercontent.com/84786032/133917238-73859860-6b27-4ce5-851d-24c2b8442a93.png)

**Comment by gunjandatta** [comment]
You should use the btnProps property to change the button type.

```ts
Components.Tooltip({
  el: document.querySelector("#tooltip"),
  content: "This is the content for the tooltip.",
  btnProps: {
    text: "My Tooltip",
    type: Components.ButtonTypes.Danger
  },
  options: {
    // theme property applies to the tippyjs theme
    // https://atomiks.github.io/tippyjs/v6/themes/
  }
});
```
